name: clang-format-check
on: [pull_request, push]

jobs:
  build:
    name: clang-format-check
    runs-on: ubuntu-20.04
    if: github.event_name == 'pull_request'

    steps:
        - name: Fetch repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Install packages
          run: sudo apt-get update && sudo apt-get install python3-venv
        - name: check_clang_format
          run: ci/check_clang_format.sh
